export interface DailyTopic {
  dayOfWeek: number; // 0=Sunday, 1=Monday, ..., 6=Saturday
  dayName: string;
  leader: 'efo' | 'daavi';
  title: string;
  subtitle: string;
  emoji: string;
  color: string; // CSS gradient for inline style
  questions: string[];
}

export const DAILY_TOPICS: DailyTopic[] = [
  {
    dayOfWeek: 0,
    dayName: 'Sunday',
    leader: 'efo',
    title: 'Love Languages & Emotional Connection',
    subtitle: 'Understanding how we give and receive love',
    emoji: '💗',
    color: 'linear-gradient(135deg, #f43f5e 0%, #be185d 100%)',
    questions: [
      'What is your primary love language, and has it changed since we started dating?',
      'Describe a specific moment when you felt most deeply loved by me — what made it so powerful?',
      'What small, everyday act of mine makes you feel the most seen and cared for?',
      'Is there a way I express love that doesn\'t land for you the way I intend it to?',
      'What does emotional intimacy feel like to you — how do you know when you truly feel close to someone?',
      'What rituals or routines help you feel most connected to me on a daily basis?',
      'When do you feel emotionally safest with me — what conditions create that safety?',
      'Is there something you need from me emotionally that you haven\'t been able to ask for yet?',
      'How do you feel love differently when you\'re stressed versus when things are calm?',
      'What does it mean to you to be truly known by a partner — not just loved, but deeply understood?',
      'How do you express love differently to me than you have with anyone else?',
      'What\'s a moment when you felt my love was especially unconditional?',
      'Do you ever feel emotionally lonely inside our relationship, even when we\'re physically together?',
      'What does being emotionally present with a partner look like to you in practice?',
      'How do you feel about vulnerability — is it easy or hard for you to let me into your inner world?',
      'What\'s something about the way I love you that surprised you when you first noticed it?',
      'How do you feel about saying "I love you" — does the phrase feel full or hollow depending on the moment?',
      'What part of your heart have you most fully opened to me that you\'ve never opened to anyone else?',
      'Is there a love language you wish I would use more, even if it doesn\'t come naturally to me?',
      'When you imagine us 10 years from now, what does your emotional connection look and feel like?',
      'What does it mean to you when I choose you — not out of obligation, but because I genuinely want to?',
      'How would you describe the quality of our emotional connection to someone who asked you about our relationship?',
    ],
  },
  {
    dayOfWeek: 1,
    dayName: 'Monday',
    leader: 'efo',
    title: 'Trust & Vulnerability',
    subtitle: 'Being fully known and fully safe',
    emoji: '🔐',
    color: 'linear-gradient(135deg, #111827 0%, #000000 100%)',
    questions: [
      'What does trust mean to you at its deepest level — beyond just not lying?',
      'What\'s one fear about being fully known that you still carry, even with me?',
      'Describe a past experience that deeply shaped your ability to trust a romantic partner.',
      'Has there been a moment in our relationship when you felt your trust in me waver? What happened?',
      'What would I need to do — or stop doing — to make you feel more emotionally safe with me?',
      'Is there a part of yourself you still hide from me because you\'re afraid of how I\'d respond?',
      'What does it feel like in your body when you\'re with someone you truly trust?',
      'How do you know when you\'ve genuinely forgiven someone — what does that feel like inside you?',
      'What\'s a secret fear about yourself that you\'ve never fully voiced, even to me?',
      'When you\'ve been at your absolute worst — dark, broken, struggling — do you trust I would still stay?',
      'What does betrayal mean to you, and what forms of it are hardest for you to recover from?',
      'Is there something you\'ve never told me about your past because you\'re afraid it would change how I see you?',
      'How do you rebuild trust after it\'s been damaged — what does that process look like for you?',
      'What\'s the most vulnerable thing you\'ve ever allowed yourself to feel in front of me?',
      'Do you feel like you can be emotionally honest with me even when the truth is uncomfortable?',
      'What does it mean to you when I keep my word — even on small things?',
      'Are there stories from your childhood that you\'ve never shared with me that you think I should know?',
      'How do you feel about the idea that true intimacy requires showing someone your worst self?',
      'What\'s one thing you genuinely trust about me that you find hard to trust in people generally?',
      'Do you believe I see you clearly — not just your good parts, but your shadow side too?',
      'What would it mean to you if I told you there\'s nothing you could show me that would make me leave?',
      'How do you practice emotional honesty with yourself, before you can practice it with me?',
    ],
  },
  {
    dayOfWeek: 2,
    dayName: 'Tuesday',
    leader: 'daavi',
    title: 'Intimacy & Desire',
    subtitle: 'Closeness, attraction, and being wanted',
    emoji: '🌹',
    color: 'linear-gradient(135deg, #e11d48 0%, #831843 100%)',
    questions: [
      'What does physical intimacy mean to you beyond the physical — what emotional need does it meet?',
      'When do you feel most desired by me, and what does that feeling do for you emotionally?',
      'Is there a form of physical affection — not necessarily sexual — that makes you feel most loved?',
      'What does it take for you to feel completely safe enough to be physically vulnerable with someone?',
      'How has your understanding of intimacy evolved since we\'ve been together?',
      'Is there something you need physically or sexually that you haven\'t fully communicated to me yet?',
      'What does initiating intimacy feel like for you — is it easy, scary, exciting, complicated?',
      'How important is aftercare to you — emotional or physical closeness after intimate moments?',
      'What makes you feel most attractive and confident in my presence?',
      'Do you ever feel disconnected from me physically even when we\'re close — what causes that?',
      'Is there a time you felt especially desired by me that has stayed with you?',
      'What does it mean to you when I take time and care during intimacy rather than rushing?',
      'Are there boundaries around physical intimacy that you want me to understand more deeply?',
      'How does stress, conflict, or emotional distance affect your desire for closeness with me?',
      'What\'s something about physical intimacy that you\'ve always wanted to explore but haven\'t brought up?',
      'Do you feel like your needs and desires are fully heard and honored in our intimate life?',
      'How do you feel about the role of desire over time in a long-term relationship — does it worry you?',
      'What does it feel like when I look at you with genuine desire — what does that give you?',
      'How do you communicate when something doesn\'t feel right during intimacy — is that easy or hard?',
      'What ritual or practice helps you feel most connected to me before or after intimacy?',
      'Is there a way I could make you feel more wanted in our day-to-day life, not just in intimate moments?',
      'What does it mean to you for our physical and emotional intimacy to grow together over the years?',
    ],
  },
  {
    dayOfWeek: 3,
    dayName: 'Wednesday',
    leader: 'efo',
    title: 'Boundaries & Respect',
    subtitle: 'What we need to feel safe and honored',
    emoji: '🛡️',
    color: 'linear-gradient(135deg, #1f2937 0%, #030712 100%)',
    questions: [
      'What\'s your most important non-negotiable in a relationship — the one thing that, if crossed, breaks everything?',
      'How do you typically communicate when a boundary has been crossed — directly, quietly, or do you shut down?',
      'Is there a boundary of yours that I\'ve crossed without realizing it? Can you describe what happened?',
      'How do you feel about personal space and alone time — how much do you need, and does our relationship honor that?',
      'What does it look like when you feel your autonomy is being respected inside our relationship?',
      'Are there social boundaries — around friendships, exes, or interactions with others — that we haven\'t fully discussed?',
      'How do you feel about privacy between us — phones, journals, conversations with others?',
      'What financial boundaries matter to you, and how do you want us to handle money individually and together?',
      'Do you feel like your personal values and beliefs are respected by me, even when we disagree?',
      'Is there anything in our relationship dynamic that sometimes makes you feel controlled or not free?',
      'How do you want to handle boundaries with our families — when do they come first vs. us?',
      'What does healthy independence look like to you within a committed relationship?',
      'How do you feel when I set a boundary with you — does it feel like rejection or like healthy self-respect?',
      'Is there a boundary you\'ve been afraid to express because you thought I\'d be hurt or angry?',
      'How do you approach respecting my boundaries even when they\'re inconvenient for you?',
      'What happens to your sense of self when you\'re in a relationship — do you keep yourself, or do you lose yourself?',
      'Are there topics or conversations that feel off-limits to you, and do you feel safe saying so?',
      'How do you want us to handle disagreements about boundaries — who decides what\'s fair?',
      'What does it mean to you to feel safe within our relationship — emotionally, physically, socially?',
      'Are there any patterns from past relationships around boundaries that you\'re still working through?',
      'How do you know when you\'re honoring your own boundaries versus just being rigid or defensive?',
      'What would our relationship look like if we both felt completely free and completely committed at the same time?',
    ],
  },
  {
    dayOfWeek: 4,
    dayName: 'Thursday',
    leader: 'daavi',
    title: 'Future & Life Goals',
    subtitle: 'The life we\'re building together',
    emoji: '🌅',
    color: 'linear-gradient(135deg, #db2777 0%, #9f1239 100%)',
    questions: [
      'Where do you see yourself in 5 years — and where do you see us?',
      'How do you think about children — do you want them, when, how many, and what kind of parents do you want to be?',
      'What does your dream home look, feel, and function like — and where in the world is it?',
      'How do you want us to handle finances as we grow together — separate, merged, or somewhere in between?',
      'What does career success mean to you, and how does our relationship fit into that ambition?',
      'Are there places in the world you need to live before you feel your life is complete?',
      'What traditions do you want to build together — annual trips, rituals, celebrations that are uniquely ours?',
      'How do you imagine us navigating major life decisions — who carries which responsibilities?',
      'What does retirement mean to you — what does the end of your working years look like?',
      'What kind of legacy do you want to leave — for your family, your community, the world?',
      'How do you balance your individual dreams with our shared ones — where do they conflict?',
      'What\'s a dream you haven\'t told many people that you hope this relationship can help you achieve?',
      'How do you feel about where we are in our relationship timeline — are we moving at the right pace for you?',
      'What are the three things you want most from your life in the next decade?',
      'How do you want to handle conflict about the future when we want different things?',
      'Is there a version of our future that excites you and also terrifies you?',
      'What role does faith, spirituality, or values play in how you want to build our future?',
      'How do you want to grow as an individual inside this relationship — not just as a couple?',
      'What does financial freedom mean to you, and how do we get there together?',
      'Are there things about your family\'s patterns you want to consciously break when we build our own life?',
      'What does a good, full life look like to you — and am I in the center of it?',
      'If we could design the next 10 years together right now, what would you make absolutely certain is in it?',
    ],
  },
  {
    dayOfWeek: 5,
    dayName: 'Friday',
    leader: 'efo',
    title: 'Communication & Conflict',
    subtitle: 'Fighting for each other, not against each other',
    emoji: '🗣️',
    color: 'linear-gradient(135deg, #111827 0%, #4c0519 100%)',
    questions: [
      'What\'s your default communication style when you\'re upset — do you withdraw, attack, shut down, or something else?',
      'What do you need from me in the middle of a conflict — space, closeness, words, or silence?',
      'What makes you feel most heard during a disagreement — what does active listening look like from my end?',
      'Is there something I do during arguments that makes it very hard for you to stay present?',
      'What\'s the difference for you between a healthy argument and a destructive one?',
      'How do you know when you\'ve genuinely forgiven me after a fight — what does that feel like?',
      'What does a good apology look like to you — what needs to be in it for it to actually land?',
      'Are there recurring topics we argue about that you think signal something deeper we haven\'t addressed?',
      'How do you feel about stonewalling — going silent, shutting down — and how does it affect you when I do it?',
      'What unspoken issues do you think we carry into our conflicts without naming them directly?',
      'How do you communicate a need without it becoming a complaint or an accusation?',
      'What does it look like when you\'re starting to shut down emotionally — what are your early signs?',
      'Is there a way I could approach you during conflict that would make you feel safer to stay open?',
      'How do you feel about the concept of repair — fixing the connection after a fight? Are we good at it?',
      'What communication habits from your childhood home do you carry into our relationship?',
      'Do you feel like you can tell me hard truths without it escalating into something bigger?',
      'What\'s one thing I consistently misunderstand about how you communicate when you\'re hurting?',
      'How do you want us to handle conflict in front of others — or in writing vs. in person?',
      'What does emotional flooding feel like for you — when you\'re too overwhelmed to keep talking?',
      'How important are daily check-ins to you — little moments of honest connection each day?',
      'What would our communication look like at its best — what would change from how it is now?',
      'If you could teach me one thing about how to communicate with you better, what would it be?',
    ],
  },
  {
    dayOfWeek: 6,
    dayName: 'Saturday',
    leader: 'daavi',
    title: 'Gratitude & Growth',
    subtitle: 'Who we\'re becoming together',
    emoji: '🌱',
    color: 'linear-gradient(135deg, #f43f5e 0%, #000000 100%)',
    questions: [
      'How has this relationship changed you — who are you now that you couldn\'t have been without us?',
      'What are you most genuinely grateful for about me — not what I do, but who I am?',
      'Is there a wound from your past that being in this relationship has helped you begin to heal?',
      'What\'s a milestone in our relationship that you feel we haven\'t properly celebrated?',
      'How has your sense of self grown since we\'ve been together — what have you discovered about yourself?',
      'What\'s something you\'ve had to let go of — a belief, a fear, a habit — because of loving me?',
      'How do you practice gratitude in your daily life, and does it include gratitude for our relationship?',
      'What\'s a version of yourself that this relationship is helping you grow into?',
      'Is there something about our journey together that you think people on the outside don\'t fully understand?',
      'What\'s the most unexpected way loving me has stretched you or challenged you to become better?',
      'How do you want to celebrate each other as individuals — not just as a couple?',
      'What\'s a chapter of your life, before me, that shaped you in a way I should understand more deeply?',
      'Who do you want to become in the next 5 years, and how can I help you get there?',
      'What does personal development mean to you — and how do you feel about growing alongside a partner?',
      'Is there a pattern in yourself that you\'re actively working to change, and how can I support that?',
      'What do you think makes two people genuinely good for each other — not just in love, but good for each other?',
      'What moment in our relationship are you most proud of how we handled it together?',
      'How do you feel about aging together — what excites or frightens you about growing old with me?',
      'What story about us do you want to tell when we\'re old — the one that captures who we were?',
      'What does it mean to you to be someone\'s person — their real one, their chosen one?',
      'What are you still learning about yourself through loving me?',
      'What do you want to thank me for that you\'ve never found quite the right moment to say?',
    ],
  },
];
