export const PICK_NUMBER_QUESTIONS = [
  { number: 1, category: 'Romantic', question: 'What is your favorite memory of us?' },
  { number: 2, category: 'Romantic', question: 'When did you first realize you were falling for me?' },
  { number: 3, category: 'Romantic', question: 'What is the most romantic thing I have ever done for you?' },
  { number: 4, category: 'Romantic', question: 'Describe our perfect day together.' },
  { number: 5, category: 'Romantic', question: 'What is your favorite way I show you love?' },
  { number: 6, category: 'Romantic', question: 'Which part of our love story do you want to repeat forever?' },
  { number: 7, category: 'Romantic', question: 'What song reminds you of me and why?' },
  { number: 8, category: 'Romantic', question: 'What do you love most about our relationship?' },
  { number: 9, category: 'Romantic', question: 'How has being with me changed your life?' },
  { number: 10, category: 'Romantic', question: 'What is your favorite moment between us this month?' },
  { number: 11, category: 'Deep', question: 'What does love mean to you?' },
  { number: 12, category: 'Deep', question: 'What is your biggest fear and how can I help?' },
  { number: 13, category: 'Deep', question: 'What is one thing you wish we talked about more?' },
  { number: 14, category: 'Deep', question: 'What does home feel like to you?' },
  { number: 15, category: 'Deep', question: 'What is the most important lesson love has taught you?' },
  { number: 16, category: 'Deep', question: 'How do you define happiness?' },
  { number: 17, category: 'Deep', question: 'What is something you want to experience before you die?' },
  { number: 18, category: 'Deep', question: 'How do you handle feeling lonely even when we are together?' },
  { number: 19, category: 'Deep', question: 'What would you tell your younger self about love?' },
  { number: 20, category: 'Deep', question: 'What is your love language and how can I serve it better?' },
  { number: 21, category: 'Appreciation', question: 'What is one thing I do that always makes you smile?' },
  { number: 22, category: 'Appreciation', question: 'What is something I have done this week that meant a lot to you?' },
  { number: 23, category: 'Appreciation', question: 'What is something you appreciate about me that you have not said lately?' },
  { number: 24, category: 'Appreciation', question: 'What do you love about the way I treat you?' },
  { number: 25, category: 'Appreciation', question: 'What is something you are proud of me for?' },
  { number: 26, category: 'Appreciation', question: 'How has my support helped you grow?' },
  { number: 27, category: 'Appreciation', question: 'What is a quality of mine you wish you had?' },
  { number: 28, category: 'Appreciation', question: 'What do I do that makes you feel truly loved?' },
  { number: 29, category: 'Appreciation', question: 'What is something small I do that makes a big difference?' },
  { number: 30, category: 'Appreciation', question: 'What is your favorite thing about us as a team?' },
  { number: 31, category: 'Future Goals', question: 'Where do you see us in 5 years?' },
  { number: 32, category: 'Future Goals', question: 'What future adventure should we plan together?' },
  { number: 33, category: 'Future Goals', question: 'What kind of home do you want us to build?' },
  { number: 34, category: 'Future Goals', question: 'What traditions do you want us to create?' },
  { number: 35, category: 'Future Goals', question: 'What is one goal you want us to achieve together this year?' },
  { number: 36, category: 'Future Goals', question: 'How many children do you see us having?' },
  { number: 37, category: 'Future Goals', question: 'What place in the world do you most want to visit with me?' },
  { number: 38, category: 'Future Goals', question: 'What legacy do you want us to leave together?' },
  { number: 39, category: 'Funny', question: 'What would our reality TV show be called?' },
  { number: 40, category: 'Funny', question: 'What is my most embarrassing habit?' },
  { number: 41, category: 'Funny', question: 'If I were an animal, what would I be?' },
  { number: 42, category: 'Funny', question: 'What is the funniest thing I have ever said?' },
  { number: 43, category: 'Funny', question: 'What would our signature couple dance move be?' },
  { number: 44, category: 'Funny', question: 'If we had a theme song, what would it be?' },
  { number: 45, category: 'Growth', question: 'What is one area you feel we could communicate better?' },
  { number: 46, category: 'Growth', question: 'What is something we have overcome together that made us stronger?' },
  { number: 47, category: 'Growth', question: 'What is one thing you wish I understood better about you?' },
  { number: 48, category: 'Growth', question: 'How can I be a better partner to you?' },
  { number: 49, category: 'Growth', question: 'What habit would you like us to build together?' },
  { number: 50, category: 'Growth', question: 'What does your ideal conflict resolution look like?' },
];

export const TRUTH_PROMPTS = [
  'What is the most embarrassing thing you have done in front of me?',
  'What do you secretly wish I would do more often?',
  'What is something you have never told me?',
  'What was your first impression of me?',
  'What is your biggest insecurity?',
  'What do you find most attractive about me?',
  'Have you ever lied to me? What about?',
  'What is the most romantic dream you have had about me?',
  'What is one thing about our relationship you would change?',
  'What is a habit of mine that sometimes annoys you?',
  'What is the sweetest thing I have ever done for you?',
  'What was the exact moment you knew you loved me?',
  'What is something you want to try together but have been scared to say?',
  'What makes you feel most loved by me?',
  'What was the happiest day of your life so far?',
];

export const DARE_PROMPTS = [
  'Send me the most embarrassing photo from your camera roll right now.',
  'Write me a love poem in the next 2 minutes.',
  'Tell me three things you absolutely love about me.',
  'Send a voice note saying how much I mean to you.',
  'Re-enact how you would have asked me out if you had done it differently.',
  'Dance to the next song that comes on and send me a video.',
  'Write a heartfelt text to me as if we were meeting for the first time.',
  'Plan our next date night right now.',
  'Rate me out of 10 in five different categories — and explain each.',
  'Tell me your favorite memory of us in full detail.',
  'Say something in a different language that describes how you feel about me.',
  'Give me a list of 5 things that make you proud of our relationship.',
  'Describe our future in exactly 10 sentences.',
  'Tell me what you would do if you could give me any gift in the world.',
  'Record a 30-second voice note telling me why you chose me.',
];

export const WOULD_YOU_RATHER = [
  { id: 1, a: 'Have a quiet romantic dinner at home', b: 'Go on a surprise adventure date' },
  { id: 2, a: 'Know everything about the future', b: 'Be able to relive any past moment' },
  { id: 3, a: 'Always have romantic music playing', b: 'Always have perfect weather on our dates' },
  { id: 4, a: 'Travel the world together for a year', b: 'Build our dream home together now' },
  { id: 5, a: 'Have a big beautiful wedding', b: 'Elope and spend the money on travel' },
  { id: 6, a: 'Grow old together in the same town', b: 'Live in a new city every 5 years' },
  { id: 7, a: 'Be each other\'s first love', b: 'Know we will always be each other\'s last' },
  { id: 8, a: 'Have a huge group of couple friends', b: 'Keep our relationship deeply private' },
  { id: 9, a: 'Never fight but also never fully resolve things', b: 'Fight openly but always make up stronger' },
  { id: 10, a: 'Live closer to your family', b: 'Live closer to my family' },
  { id: 11, a: 'Communicate only through love letters for a week', b: 'Spend an entire weekend in complete silence' },
  { id: 12, a: 'Know exactly what the other is thinking', b: 'Always feel exactly what the other is feeling' },
  { id: 13, a: 'Have our love story made into a movie', b: 'Have our love story written into a bestselling book' },
  { id: 14, a: 'Never have money problems again', b: 'Never have any more health problems again' },
  { id: 15, a: 'Take a spontaneous trip every month', b: 'Take one epic trip every year together' },
];

export const THIS_OR_THAT = [
  { id: 1, a: 'Coffee ☕', b: 'Tea 🍵' },
  { id: 2, a: 'Beach 🏖️', b: 'Mountains 🏔️' },
  { id: 3, a: 'Movie night in 🎬', b: 'Dinner out 🍽️' },
  { id: 4, a: 'Morning person 🌅', b: 'Night owl 🦉' },
  { id: 5, a: 'Surprise gifts 🎁', b: 'Planned gifts 🎀' },
  { id: 6, a: 'Pizza 🍕', b: 'Pasta 🍝' },
  { id: 7, a: 'City life 🌆', b: 'Country life 🌄' },
  { id: 8, a: 'Texting 💬', b: 'Calling 📞' },
  { id: 9, a: 'Physical touch 🤗', b: 'Quality time ⏰' },
  { id: 10, a: 'Spontaneous plans', b: 'Carefully planned dates' },
  { id: 11, a: 'Action movies 🎬', b: 'Romance movies 💕' },
  { id: 12, a: 'Cooking together 👨‍🍳', b: 'Ordering in 📱' },
  { id: 13, a: 'Summer 🌞', b: 'Winter ❄️' },
  { id: 14, a: 'Dogs 🐕', b: 'Cats 🐈' },
  { id: 15, a: 'Save money 💰', b: 'Spend on experiences 🌍' },
];
